name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Publish to registry.npmjs.com
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          pnpm run build
          pnpm publish --no-git-checks

      - name: Setup git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Create release body
        id: cliff
        run: echo "RELEASE_BODY=$(git cliff -l --strip header)" >> $GITHUB_OUTPUT

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: ${{ steps.cliff.outputs.RELEASE_BODY }}
