name: Release

on:
  release:
    types:
      - published
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  draft:
    name: Create draft release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0

      - name: Setup git-cliff
        uses: kenji-miyake/setup-git-cliff@2778609c643a39a2576c4bae2e493b855eb4aee8 # v2

      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        id: changelog
        with:
          result-encoding: string
          script: |
            const { stdout } = await exec.getExecOutput('git', ['cliff', '-l', '--strip', 'header'])
            return stdout

      - name: Create draft release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          draft: true
          body: ${{ steps.changelog.outputs.result }}

  publish:
    name: Publish to JSR
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish (dry-run)
        run: deno publish --dry-run

      - name: Publish
        run: deno publish
