name: Tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint

      - name: Run formatter
        run: deno fmt --check

      - name: Run tests
        run: deno test -A --coverage=coverage

      - name: Create coverage report
        run: deno coverage ./coverage --lcov --output=coverage.lcov

      - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          file: ./coverage.lcov

      - name: Publish (dry run)
        run: deno publish --dry-run
